<?php

/**
 * Authoritative puzzle blueprints (levels 1–10 mirror the mobile LEVELS array).
 * Procedural levels (11+) reuse this geometry (letters count, grid_layout) but
 * substitute words from config/procedural_word_pools.php, then persist rows.
 */
return [
    [
        'name' => 'Christmas Eve',
        'theme' => 'christmas_eve',
        'difficulty' => 'Easy',
        'letters' => ['C', 'A', 'T', 'S'],
        'words' => ['CATS', 'ACT', 'SAT'],
        'grid_words' => ['CATS', 'ACT', 'SAT'],
        'grid_layout' => [
            ['word' => 'CATS', 'row' => 0, 'col' => 0, 'direction' => 'h'],
            ['word' => 'ACT', 'row' => 0, 'col' => 1, 'direction' => 'v'],
            ['word' => 'SAT', 'row' => 0, 'col' => 3, 'direction' => 'v'],
        ],
        'background_color' => '#0B1A0D',
        'accent_color' => '#2E7D32',
        'background_image' => 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 50,
    ],
    [
        'name' => 'Winter Wonderland',
        'theme' => 'winter',
        'difficulty' => 'Easy',
        'letters' => ['S', 'T', 'A', 'R'],
        'words' => ['STAR', 'ART', 'RATS'],
        'grid_words' => ['STAR', 'ART', 'RATS'],
        'grid_layout' => [
            ['word' => 'STAR', 'row' => 0, 'col' => 0, 'direction' => 'h'],
            ['word' => 'ART', 'row' => 0, 'col' => 2, 'direction' => 'v'],
            ['word' => 'RATS', 'row' => 0, 'col' => 3, 'direction' => 'v'],
        ],
        'background_color' => '#0A1520',
        'accent_color' => '#87CEEB',
        'background_image' => 'https://images.unsplash.com/photo-1457269449834-928af64c684d?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 75,
    ],
    [
        'name' => "Santa's Workshop",
        'theme' => 'santa',
        'difficulty' => 'Medium',
        'letters' => ['S', 'T', 'O', 'N', 'E'],
        'words' => ['STONE', 'NOSE', 'NOTE', 'TONE'],
        'grid_words' => ['STONE', 'NOSE', 'NOTE', 'TONE'],
        'grid_layout' => [
            ['word' => 'STONE', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'NOSE', 'row' => 0, 'col' => 0, 'direction' => 'v'],
            ['word' => 'NOTE', 'row' => 0, 'col' => 1, 'direction' => 'v'],
            ['word' => 'TONE', 'row' => 1, 'col' => 2, 'direction' => 'v'],
        ],
        'background_color' => '#0F1A0A',
        'accent_color' => '#FFD700',
        'background_image' => 'https://images.unsplash.com/photo-1513885535751-8b9238a45a0d?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 100,
    ],
    [
        'name' => 'Northern Lights',
        'theme' => 'aurora',
        'difficulty' => 'Medium',
        'letters' => ['S', 'T', 'U', 'D', 'Y'],
        'words' => ['STUDY', 'DUST', 'DUTY'],
        'grid_words' => ['STUDY', 'DUST', 'DUTY'],
        'grid_layout' => [
            ['word' => 'STUDY', 'row' => 1, 'col' => 0, 'direction' => 'h'],
            ['word' => 'DUST', 'row' => 0, 'col' => 2, 'direction' => 'v'],
            ['word' => 'DUTY', 'row' => 1, 'col' => 3, 'direction' => 'v'],
        ],
        'background_color' => '#0A0D1A',
        'accent_color' => '#7B68EE',
        'background_image' => 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 150,
    ],
    [
        'name' => 'Candy Cane Lane',
        'theme' => 'candy',
        'difficulty' => 'Medium',
        'letters' => ['P', 'E', 'N', 'C', 'I', 'L'],
        'words' => ['PENCIL', 'PINE', 'NICE', 'ICE'],
        'grid_words' => ['PENCIL', 'PINE', 'NICE', 'ICE'],
        'grid_layout' => [
            ['word' => 'PENCIL', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'PINE', 'row' => 0, 'col' => 2, 'direction' => 'v'],
            ['word' => 'NICE', 'row' => 0, 'col' => 3, 'direction' => 'v'],
            ['word' => 'ICE', 'row' => 2, 'col' => 4, 'direction' => 'v'],
        ],
        'background_color' => '#120A14',
        'accent_color' => '#FF69B4',
        'background_image' => 'https://images.unsplash.com/photo-1512389142860-9c449e58a814?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 200,
    ],
    [
        'name' => 'Midnight Mass',
        'theme' => 'christmas_eve',
        'difficulty' => 'Medium',
        'letters' => ['T', 'E', 'A', 'C', 'H', 'R'],
        'words' => ['TEACH', 'EACH', 'ARCH', 'CHAT'],
        'grid_words' => ['TEACH', 'EACH', 'ARCH', 'CHAT'],
        'grid_layout' => [
            ['word' => 'TEACH', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'EACH', 'row' => 0, 'col' => 3, 'direction' => 'v'],
            ['word' => 'ARCH', 'row' => 2, 'col' => 2, 'direction' => 'v'],
            ['word' => 'CHAT', 'row' => 1, 'col' => 4, 'direction' => 'v'],
        ],
        'background_color' => '#0B1A0D',
        'accent_color' => '#388E3C',
        'background_image' => 'https://images.unsplash.com/photo-1513297887119-d46691b37682?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 125,
    ],
    [
        'name' => 'Frosty Morning',
        'theme' => 'winter',
        'difficulty' => 'Hard',
        'letters' => ['W', 'A', 'T', 'E', 'R', 'S'],
        'words' => ['WATER', 'STEW', 'SWEAR', 'TEARS'],
        'grid_words' => ['WATER', 'STEW', 'SWEAR', 'TEARS'],
        'grid_layout' => [
            ['word' => 'WATER', 'row' => 1, 'col' => 0, 'direction' => 'h'],
            ['word' => 'STEW', 'row' => 0, 'col' => 2, 'direction' => 'v'],
            ['word' => 'SWEAR', 'row' => 0, 'col' => 0, 'direction' => 'v'],
            ['word' => 'TEARS', 'row' => 0, 'col' => 3, 'direction' => 'v'],
        ],
        'background_color' => '#0A1520',
        'accent_color' => '#B0E0E6',
        'background_image' => 'https://images.unsplash.com/photo-1483664852095-d6cc04af2cfe?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 150,
    ],
    [
        'name' => 'Gingerbread House',
        'theme' => 'santa',
        'difficulty' => 'Hard',
        'letters' => ['P', 'L', 'A', 'N', 'E', 'T'],
        'words' => ['PLANET', 'PANE', 'PETAL', 'LATE'],
        'grid_words' => ['PLANET', 'PANE', 'PETAL', 'LATE'],
        'grid_layout' => [
            ['word' => 'PLANET', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'PANE', 'row' => 0, 'col' => 3, 'direction' => 'v'],
            ['word' => 'PETAL', 'row' => 1, 'col' => 4, 'direction' => 'v'],
            ['word' => 'LATE', 'row' => 0, 'col' => 5, 'direction' => 'v'],
        ],
        'background_color' => '#0F1A0A',
        'accent_color' => '#F5B800',
        'background_image' => 'https://images.unsplash.com/photo-1511268551654-f0c421622f17?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 200,
    ],
    [
        'name' => 'Starry Holy Night',
        'theme' => 'aurora',
        'difficulty' => 'Hard',
        'letters' => ['M', 'I', 'N', 'D', 'S', 'E', 'T'],
        'words' => ['MINDSET', 'MIST', 'DINE', 'TEND'],
        'grid_words' => ['MINDSET', 'MIST', 'DINE', 'TEND'],
        'grid_layout' => [
            ['word' => 'MINDSET', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'MIST', 'row' => 1, 'col' => 1, 'direction' => 'v'],
            ['word' => 'DINE', 'row' => 2, 'col' => 3, 'direction' => 'v'],
            ['word' => 'TEND', 'row' => 1, 'col' => 5, 'direction' => 'v'],
        ],
        'background_color' => '#0A0A1F',
        'accent_color' => '#9370DB',
        'background_image' => 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 250,
    ],
    [
        'name' => 'Ice Palace',
        'theme' => 'candy',
        'difficulty' => 'Expert',
        'letters' => ['F', 'R', 'O', 'S', 'T', 'Y'],
        'words' => ['FROSTY', 'STORY', 'SORT', 'ROSY', 'FORT'],
        'grid_words' => ['FROSTY', 'STORY', 'SORT', 'ROSY', 'FORT'],
        'grid_layout' => [
            ['word' => 'FROSTY', 'row' => 2, 'col' => 0, 'direction' => 'h'],
            ['word' => 'STORY', 'row' => 0, 'col' => 2, 'direction' => 'v'],
            ['word' => 'SORT', 'row' => 2, 'col' => 3, 'direction' => 'v'],
            ['word' => 'ROSY', 'row' => 2, 'col' => 1, 'direction' => 'v'],
            ['word' => 'FORT', 'row' => 2, 'col' => 0, 'direction' => 'v'],
        ],
        'background_color' => '#150A1F',
        'accent_color' => '#E91E9C',
        'background_image' => 'https://images.unsplash.com/photo-1477601263568-180e2c6d046e?auto=format&fit=crop&w=1800&q=90',
        'grid_style' => 'circle',
        'reward' => 300,
    ],
];
