<?php

/**
 * Display names for game levels 1–100. Levels above 100 cycle this list with Roman suffixes
 * (101–200 → " I", 201–300 → " II", etc.). Resolved by App\Services\Game\LevelNameResolver.
 */
return [
    'Christmas Eve',
    'Winter Wonderland',
    'Santa\'s Workshop',
    'Frosty Morning',
    'Candy Cane Lane',
    'Holiday Lights',
    'Snow Day',
    'Cozy Fireplace',
    'Reindeer Trail',
    'Jingle Bells',
    'North Pole Express',
    'Gingerbread House',
    'Christmas Cookies',
    'Snowflake Valley',
    'Holiday Cheer',
    'Sleigh Ride',
    'Evergreen Forest',
    'Stocking Stuffer',
    'Mistletoe Magic',
    'Winter Wishes',
    'Silent Night',
    'Frozen Pond',
    'Toymaker\'s Village',
    'Snow Globe',
    'Holly & Ivy',
    'Peppermint Path',
    'Christmas Market',
    'Ice Crystal Cave',
    'Caroling Night',
    'Santa\'s Mailroom',
    'Polar Star',
    'Blizzard Peak',
    'Arctic Adventure',
    'Rudolph\'s Run',
    'Winter Cabin',
    'Yuletide Trail',
    'Holiday Harbor',
    'Frozen Forest',
    'Santa\'s Stable',
    'Twinkling Tundra',
    'Northern Lights',
    'Icicle Ridge',
    'Elf Headquarters',
    'Snowy Summit',
    'Gift Factory',
    'Winter Castle',
    'Crystal Crossing',
    'Holiday Junction',
    'Reindeer Crossing',
    'Christmas Kingdom',
    'Polar Expedition',
    'Frostbite Falls',
    'Evergreen Heights',
    'Ice Lantern Trail',
    'Winter Festival',
    'Sugar Plum Village',
    'Sleigh Bell Pass',
    'Snowdrift Canyon',
    'Frozen Frontier',
    'Santa\'s Secret Route',
    'Arctic Outpost',
    'Moonlit Snowfield',
    'Frostfire Mountain',
    'Icebound Village',
    'Enchanted Evergreen',
    'Winter Whispers',
    'Crystal Forest',
    'Blizzard Crossing',
    'Reindeer Raceway',
    'Holiday Highlands',
    'Aurora Valley',
    'Ice Palace',
    'Snowstorm Pass',
    'Santa\'s Citadel',
    'Polar Fortress',
    'Frozen Kingdom',
    'Christmas Chronicles',
    'Winter Dominion',
    'Frost Guardian',
    'Starlight Summit',
    'Northern Crown',
    'Crystal Citadel',
    'Blizzard Throne',
    'Winter Realm',
    'Arctic Legends',
    'Santa\'s Stronghold',
    'Frost King\'s Path',
    'Celestial Snowfall',
    'Aurora Kingdom',
    'Eternal Winter',
    'Holiday Legends',
    'Frozen Empire',
    'Star of Bethlehem',
    'Christmas Miracle',
    'Winter Destiny',
    'The Great Blizzard',
    'Santa\'s Legacy',
    'Polar Paradise',
    'Christmas Eternity',
    'The North Pole Throne',
];
