<?php

/**
 * Words for procedural levels (11+). Ordered roughly common → more obscure within each length.
 * Generator skips words that appear in game_level_blueprints (levels 1–10).
 * Client still normalizes to singular uppercase; use singular dictionary forms here.
 */
return [
    3 => [
        'ANT', 'APT', 'ARC', 'ARM', 'ASH', 'AWE', 'AXE', 'BAD', 'BAG', 'BAN', 'BAR', 'BAT', 'BAY',
        'BED', 'BET', 'BID', 'BIG', 'BIN', 'BIT', 'BOG', 'BOP', 'BOT', 'BOW', 'BOX', 'BUD', 'BUG',
        'BUN', 'BUS', 'BUT', 'BUY', 'CAB', 'CAM', 'CAN', 'CAP', 'CAR', 'COB', 'COD', 'COG', 'COP',
        'COT', 'COW', 'COX', 'COY', 'CRY', 'CUB', 'CUE', 'CUP', 'CUR', 'CUT', 'DAB', 'DAD', 'DAM',
        'DEN', 'DEW', 'DID', 'DIG', 'DIM', 'DIP', 'DOC', 'DOT', 'DRY', 'DUB', 'DUD', 'DUG', 'DUN',
        'DUO', 'DYE', 'EAR', 'EAT', 'EEL', 'EGG', 'ELF', 'ELK', 'ELM', 'EMU', 'END', 'ERA', 'EVE',
        'EWE', 'EYE', 'FAD', 'FAN', 'FAR', 'FAT', 'FAX', 'FED', 'FEW', 'FIG', 'FIN', 'FIT', 'FIX',
        'FLU', 'FLY', 'FOE', 'FOG', 'FOR', 'FOX', 'FRY', 'FUN', 'FUR', 'GAP', 'GAS', 'GEL', 'GEM',
        'GET', 'GIG', 'GIN', 'GNU', 'GOB', 'GOD', 'GOT', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM', 'HAM',
        'HAT', 'HAY', 'HEM', 'HEN', 'HEW', 'HEX', 'HID', 'HIM', 'HIP', 'HIS', 'HIT', 'HOB', 'HOD',
        'HOG', 'HOP', 'HOT', 'HOW', 'HUB', 'HUE', 'HUG', 'HUM', 'HUT', 'ICE', 'ICY', 'ILK', 'IMP',
        'INK', 'INN', 'ION', 'IRE', 'IRK', 'IVY', 'JAB', 'JAG', 'JAM', 'JAR', 'JAW', 'JAY', 'JET',
        'JIG', 'JOB', 'JOG', 'JOT', 'JOY', 'JUG', 'JUT', 'KEG', 'KEN', 'KEY', 'KID', 'KIN', 'KIT',
        'LAB', 'LAC', 'LAD', 'LAG', 'LAP', 'LAW', 'LAX', 'LAY', 'LEA', 'LED', 'LEG', 'LET', 'LID',
        'LIE', 'LIP', 'LOB', 'LOG', 'LOT', 'LOW', 'LUG', 'LYE', 'MAD', 'MAN', 'MAP', 'MAR', 'MAT',
        'MAW', 'MAX', 'MAY', 'MEN', 'MET', 'MID', 'MIX', 'MOB', 'MOD', 'MOM', 'MOP', 'MOW', 'MUD',
        'MUG', 'MUM', 'NAB', 'NAG', 'NAP', 'NAY', 'NET', 'NEW', 'NIL', 'NIT', 'NOD', 'NOR', 'NOT',
        'NOW', 'NUB', 'NUN', 'NUT', 'OAK', 'OAR', 'OAT', 'ODD', 'ODE', 'OFF', 'OFT', 'OIL', 'OLD',
        'ONE', 'OPT', 'ORB', 'ORE', 'OUR', 'OUT', 'OWE', 'OWL', 'OWN', 'PAD', 'PAL', 'PAN', 'PAP',
        'PAR', 'PAT', 'PAW', 'PAY', 'PEA', 'PEG', 'PEN', 'PEP', 'PER', 'PET', 'PEW', 'PIE', 'PIG',
        'PIN', 'PIT', 'PLY', 'POD', 'POP', 'POT', 'POW', 'PRO', 'PRY', 'PUB', 'PUG', 'PUN', 'PUP',
        'PUS', 'PUT', 'RAG', 'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY', 'RED', 'REF', 'REM', 'REP',
        'RIB', 'RID', 'RIG', 'RIM', 'RIP', 'ROB', 'ROD', 'ROE', 'ROT', 'ROW', 'RUB', 'RUG', 'RUM',
        'RUN', 'RUT', 'RYE', 'SAC', 'SAD', 'SAG', 'SAP', 'SAT', 'SAW', 'SAY', 'SEA', 'SET', 'SEW',
        'SHE', 'SHY', 'SIN', 'SIP', 'SIR', 'SIS', 'SIT', 'SIX', 'SKI', 'SKY', 'SLY', 'SOB', 'SOD',
        'SON', 'SOP', 'SOT', 'SOW', 'SOY', 'SPA', 'SPY', 'STY', 'SUB', 'SUE', 'SUM', 'SUN', 'SUP',
        'TAB', 'TAD', 'TAG', 'TAN', 'TAP', 'TAR', 'TAT', 'TAX', 'TEA', 'TEN', 'THE', 'THY', 'TIC',
        'TIE', 'TIN', 'TIP', 'TOE', 'TON', 'TOO', 'TOP', 'TOT', 'TOW', 'TOY', 'TRY', 'TUB', 'TUG',
        'TUN', 'TWO', 'URN', 'USE', 'VAN', 'VAT', 'VET', 'VEX', 'VIA', 'VIE', 'VOW', 'WAD', 'WAG',
        'WAR', 'WAS', 'WAX', 'WAY', 'WEB', 'WED', 'WEE', 'WET', 'WHO', 'WHY', 'WIG', 'WIN', 'WIT',
        'WOE', 'WOK', 'WON', 'WOO', 'WOW', 'YAK', 'YAM', 'YAP', 'YAW', 'YEA', 'YEN', 'YEP', 'YES',
        'YET', 'YIN', 'YIP', 'YOU', 'YOW', 'ZAG', 'ZAP', 'ZED', 'ZEN', 'ZIP', 'ZIT',
    ],
    4 => [
        'ACHE', 'ACID', 'ACME', 'ACNE', 'AQUA', 'ARCH', 'AREA', 'ARMY', 'ATOM', 'AUNT', 'AUTO', 'AVID',
        'AWAY', 'AXIS', 'BABY', 'BACH', 'BACK', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALL', 'BALM', 'BAND',
        'BANE', 'BANK', 'BARD', 'BARE', 'BARK', 'BARN', 'BASE', 'BASH', 'BASK', 'BASS', 'BATH', 'BAWL',
        'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEND', 'BENT', 'BERG', 'BERM', 'BEST', 'BIAS',
        'BIKE', 'BILE', 'BILK', 'BIND', 'BINE', 'BIRD', 'BITE', 'BLUR', 'BOAR', 'BOAT', 'BODY', 'BOGY',
        'BOLD', 'BOLT', 'BOND', 'BONE', 'BONG', 'BONY', 'BOOK', 'BOOM', 'BOON', 'BOOT', 'BORE', 'BORN',
        'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BOXY', 'BRAD', 'BRAG', 'BRAN', 'BRAT', 'BRED', 'BREW', 'BRIM',
        'BROW', 'BUCK', 'BUDS', 'BUFF', 'BULB', 'BULK', 'BUMP', 'BUNK', 'BUNT', 'BUOY', 'BURN', 'BURR',
        'BURY', 'BUSH', 'BUSS', 'BUST', 'BUSY', 'BYTE', 'CAGE', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAME',
        'CAMP', 'CANE', 'CAPE', 'CARD', 'CARE', 'CARP', 'CART', 'CASE', 'CASH', 'CAST', 'CAVE', 'CEDE',
        'CELL', 'CENT', 'CHAP', 'CHAR', 'CHAT', 'CHEF', 'CHEW', 'CHIC', 'CHIN', 'CHIP', 'CHOP', 'CHOW',
        'CITY', 'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAY', 'CLIP', 'CLOD', 'CLOG', 'CLOP', 'CLOT', 'CLOU',
        'CLOY', 'CLUB', 'CLUE', 'COAL', 'COAT', 'COAX', 'COCK', 'CODA', 'CODE', 'COED', 'COIL', 'COIN',
        'COKE', 'COLA', 'COLD', 'COLT', 'COMA', 'COMB', 'COME', 'CONE', 'CONK', 'COOK', 'COOL', 'COON',
        'COOP', 'COOT', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN', 'COST', 'COZY', 'CRAB', 'CRAG',
        'CRAM', 'CRAW', 'CREW', 'CRIB', 'CROP', 'CROW', 'CUBE', 'CUFF', 'CULT', 'CURB', 'CURD', 'CURE',
        'CURL', 'CURT', 'CUTE', 'DAFT', 'DAIS', 'DALE', 'DAME', 'DAMP', 'DARE', 'DARK', 'DARN', 'DART',
        'DASH', 'DATA', 'DATE', 'DAUB', 'DAWN', 'DAYS', 'DEAD', 'DEAF', 'DEAL', 'DEAN', 'DEAR', 'DEBT',
        'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEFT', 'DEMO', 'DENT', 'DESK', 'DIAL', 'DICE', 'DIET',
        'DIGS', 'DIME', 'DINE', 'DING', 'DINT', 'DIRE', 'DIRK', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVE',
        'DOCK', 'DOES', 'DOFF', 'DOGE', 'DOLE', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOSE', 'DOTE', 'DOVE',
        'DOWN', 'DRAB', 'DRAG', 'DRAM', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG', 'DRUM', 'DUAL', 'DUCK',
        'DUCT', 'DUEL', 'DUET', 'DUKE', 'DULL', 'DUMB', 'DUMP', 'DUNE', 'DUNK', 'DUSK', 'DUST', 'DUTY',
        'EACH', 'EARL', 'EARN', 'EASE', 'EAST', 'ECHO', 'EDGE', 'EDIT', 'EELS', 'EGGS', 'ELAN', 'ELMS',
        'EMIT', 'EPIC', 'EURO', 'EVEN', 'EVER', 'EVIL', 'EXAM', 'EXIT', 'EXPO', 'EYED', 'FACE', 'FACT',
        'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG', 'FARM', 'FAST', 'FATE', 'FAUN', 'FAUX',
        'FAWN', 'FEAR', 'FEAT', 'FEED', 'FEEL', 'FEET', 'FELL', 'FELT', 'FERN', 'FEST', 'FEUD', 'FILE',
        'FILL', 'FILM', 'FIND', 'FINE', 'FINK', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FIVE', 'FLAK', 'FLAM',
        'FLAP', 'FLAT', 'FLAW', 'FLEA', 'FLED', 'FLEE', 'FLEW', 'FLEX', 'FLIP', 'FLOE', 'FLOG', 'FLOW',
        'FLUB', 'FLUE', 'FLUX', 'FOAL', 'FOAM', 'FOCI', 'FOGY', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT',
        'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORE', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FOWL', 'FRAY',
        'FREE', 'FRET', 'FROG', 'FROM', 'FUEL', 'FULL', 'FUME', 'FUND', 'FUNK', 'FURL', 'FUSE', 'FUSS',
        'FUZZ', 'GAFF', 'GAGA', 'GAIN', 'GAIT', 'GALA', 'GALE', 'GALL', 'GAME', 'GANG', 'GAPE', 'GARB',
        'GASH', 'GASP', 'GATE', 'GAUD', 'GAWK', 'GAZE', 'GEAR', 'GEEK', 'GELD', 'GENE', 'GIFT', 'GILD',
        'GILL', 'GILT', 'GIRD', 'GIRL', 'GIST', 'GIVE', 'GLAD', 'GLEE', 'GLEN', 'GLIB', 'GLOB', 'GLOM',
        'GLOW', 'GLUE', 'GLUM', 'GLUT', 'GOAD', 'GOAL', 'GOAT', 'GOER', 'GOES', 'GOLD', 'GOLF', 'GONE',
        'GONG', 'GOOD', 'GOOF', 'GORE', 'GORY', 'GOSH', 'GOUT', 'GOWN', 'GRAB', 'GRAD', 'GRAM', 'GRAY',
        'GREW', 'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROW', 'GRUB', 'GULF', 'GULL', 'GULP',
        'GUMS', 'GUNK', 'GURU', 'GUSH', 'GUST', 'GYRO', 'HACK', 'HAIL', 'HAIR', 'HALF', 'HALL', 'HALO',
        'HALT', 'HAND', 'HANG', 'HARD', 'HARE', 'HARK', 'HARM', 'HARP', 'HASH', 'HAST', 'HATE', 'HAUL',
        'HAVE', 'HAWK', 'HAZE', 'HAZY', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HECK', 'HEED', 'HEEL',
        'HEFT', 'HEIR', 'HELD', 'HELL', 'HELM', 'HELP', 'HEMP', 'HERB', 'HERD', 'HERE', 'HERO', 'HERS',
        'HEWN', 'HICK', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HILT', 'HIND', 'HINT', 'HIRE', 'HISS', 'HIVE',
        'HOAX', 'HOCK', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HONE', 'HONK', 'HOOD', 'HOOF', 'HOOK', 'HOOP',
        'HOOT', 'HORN', 'HOSE', 'HOST', 'HOUR', 'HOVE', 'HOWL', 'HUGE', 'HULK', 'HULL', 'HUMP', 'HUNG',
        'HUNK', 'HUNT', 'HURD', 'HURL', 'HURT', 'HUSH', 'HYMN', 'HYPE', 'ICON', 'IDEA', 'IDLE', 'IDOL',
        'INCH', 'INFO', 'INKY', 'INTO', 'IOTA', 'IRIS', 'IRON', 'ISLE', 'ITCH', 'ITEM', 'JACK', 'JADE',
        'JAIL', 'JAMB', 'JANE', 'JAPE', 'JARL', 'JARS', 'JAVA', 'JAWS', 'JAZZ', 'JEAN', 'JERK', 'JEST',
        'JETS', 'JIVE', 'JOBS', 'JOCK', 'JOIN', 'JOKE', 'JOLT', 'JOWL', 'JOYS',
    ],
    5 => [
        'ABODE', 'ABORT', 'ABOUT', 'ABOVE', 'ABUSE', 'ACORN', 'ACRID', 'ACTOR', 'ACUTE', 'ADAGE', 'ADEPT',
        'ADMIN', 'ADMIT', 'ADOBE', 'ADOPT', 'ADORE', 'ADULT', 'AFIRE', 'AFTER', 'AGAIN', 'AGATE', 'AGENT',
        'AGILE', 'AGING', 'AGLOW', 'AGONY', 'AGREE', 'AHEAD', 'AISLE', 'ALARM', 'ALBUM', 'ALERT', 'ALIEN',
        'ALIGN', 'ALIKE', 'ALIVE', 'ALLEY', 'ALLOT', 'ALLOW', 'ALLOY', 'ALOFT', 'ALONE', 'ALONG', 'ALOOF',
        'ALTAR', 'ALTER', 'AMASS', 'AMAZE', 'AMBER', 'AMBLE', 'AMEND', 'AMISS', 'AMONG', 'AMPLE', 'AMPLY',
        'AMUSE', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'ANGST', 'ANIME', 'ANKLE', 'ANNOY', 'ANTIC', 'ANVIL',
        'APART', 'APPLE', 'APPLY', 'APRON', 'APTLY', 'ARBOR', 'ARGUE', 'ARISE', 'ARMOR', 'AROMA', 'AROSE',
        'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'ATLAS', 'ATOLL', 'ATONE', 'ATTIC', 'AUDIO', 'AUDIT', 'AUGUR',
        'AUNTY', 'AVAIL', 'AVERT', 'AVIAN', 'AVOID', 'AWAIT', 'AWAKE', 'AWARD', 'AWARE', 'AWFUL', 'AXIOM',
        'AZURE', 'BACON', 'BADGE', 'BADLY', 'BAGEL', 'BAKER', 'BALMY', 'BANAL', 'BANJO', 'BARGE',
        'BARON', 'BASIC', 'BASIL', 'BASIN', 'BATCH', 'BATHE', 'BATON', 'BATTY', 'BAWDY', 'BAYOU', 'BEACH',
        'BEADY', 'BEARD', 'BEAST', 'BEGET', 'BEGIN', 'BEGUN', 'BEING', 'BELCH', 'BELIE', 'BELLY', 'BELOW',
        'BENCH', 'BERET', 'BERTH', 'BESET', 'BEVEL', 'BIBLE', 'BICEP', 'BIDDY', 'BIGOT', 'BILGE', 'BILLY',
        'BINGE', 'BINGO', 'BIOME', 'BIRCH', 'BIRTH', 'BLACK', 'BLADE', 'BLAME', 'BLAND', 'BLANK', 'BLARE',
        'BLAST', 'BLAZE', 'BLEAK', 'BLEAT', 'BLEED', 'BLEEP', 'BLEND', 'BLESS', 'BLIMP', 'BLIND', 'BLINK',
        'BLISS', 'BLITZ', 'BLOAT', 'BLOCK', 'BLOKE', 'BLOND', 'BLOOD', 'BLOOM', 'BLOWN', 'BLUER', 'BLUFF',
        'BLUNT', 'BLURB', 'BLURT', 'BLUSH', 'BOARD', 'BOAST', 'BOBBY', 'BOGGY', 'BOGUS', 'BOOST', 'BOOTH',
        'BOOTY', 'BOOZE', 'BORAX', 'BORNE', 'BOSOM', 'BOSSY', 'BOTCH', 'BOUGH', 'BOUND', 'BOWEL', 'BOXER',
        'BRACE', 'BRAID', 'BRAIN', 'BRAKE', 'BRAND', 'BRASH', 'BRASS', 'BRAVE', 'BRAVO', 'BRAWL', 'BRAWN',
        'BREAD', 'BREAK', 'BREED', 'BRIBE', 'BRICK', 'BRIDE', 'BRIEF', 'BRINE', 'BRING', 'BRINK', 'BRINY',
        'BRISK', 'BROAD', 'BROIL', 'BROKE', 'BROOD', 'BROOK', 'BROOM', 'BROTH', 'BROWN', 'BRUNT', 'BRUSH',
        'BRUTE', 'BUDGE', 'BUGGY', 'BUILD', 'BUILT', 'BULGE', 'BULKY', 'BULLY', 'BUNCH', 'BUNNY', 'BURLY',
        'BURRO', 'BURST', 'BUSHY', 'BUTCH', 'BUTTE', 'BUXOM', 'BUYER', 'CABAL', 'CABBY', 'CABLE', 'CACAO',
        'CACHE', 'CACTI', 'CADDY', 'CADET', 'CAGEY', 'CAIRN', 'CAMEL', 'CAMEO', 'CANAL', 'CANDY', 'CANNY',
        'CANOE', 'CANON', 'CAPER', 'CAPUT', 'CARAT', 'CARGO', 'CAROL', 'CARRY', 'CARVE', 'CASTE', 'CATCH',
        'CATER', 'CATTY', 'CAULK', 'CAUSE', 'CAVIL', 'CEASE', 'CEDAR', 'CELLO', 'CHAFF', 'CHAIN', 'CHAIR',
        'CHALK', 'CHAMP', 'CHANT', 'CHAOS', 'CHARD', 'CHARM', 'CHART', 'CHASE', 'CHASM', 'CHEAP', 'CHEAT',
        'CHECK', 'CHEEK', 'CHEER', 'CHESS', 'CHEST', 'CHICK', 'CHIDE', 'CHIEF', 'CHILD', 'CHILI', 'CHILL',
        'CHIME', 'CHINA', 'CHIRP', 'CHOCK', 'CHOIR', 'CHOKE', 'CHORD', 'CHORE', 'CHOSE', 'CHUCK', 'CHUMP',
        'CHUNK', 'CHURN', 'CHUTE', 'CIDER', 'CIGAR', 'CINCH', 'CIRCA', 'CIVIC', 'CIVIL', 'CLACK', 'CLAIM',
        'CLAMP', 'CLANG', 'CLANK', 'CLASH', 'CLASP', 'CLASS', 'CLEAN', 'CLEAR', 'CLEFT', 'CLERK', 'CLICK',
        'CLIFF', 'CLIMB', 'CLING', 'CLINK', 'CLOAK', 'CLOCK', 'CLOGS', 'CLOMP', 'CLONE', 'CLOSE', 'CLOTH',
        'CLOUD', 'CLOUT', 'CLOVE', 'CLOWN', 'CLUCK', 'CLUED', 'CLUMP', 'CLUNG', 'COACH', 'COAST', 'COBRA',
        'COCOA', 'COLON', 'COLOR', 'COMET', 'COMIC', 'CORAL', 'COUCH', 'COUGH', 'COULD', 'COUNT', 'COURT',
        'COVEN', 'COVER', 'COVET', 'COWED', 'COWER', 'CRACK', 'CRAFT', 'CRAMP', 'CRANE', 'CRANK', 'CRASH',
        'CRASS', 'CRATE', 'CRAVE', 'CRAWL', 'CRAZE', 'CRAZY', 'CREAK', 'CREAM', 'CREDO', 'CREED', 'CREEK',
        'CREEP', 'CREME', 'CREPE', 'CREPT', 'CRESS', 'CREST', 'CRICK', 'CRIED', 'CRIER', 'CRIME', 'CRIMP',
        'CRISP', 'CROAK', 'CROCK', 'CRONE', 'CRONY', 'CROOK', 'CROSS', 'CROUP', 'CROWD', 'CROWN', 'CRUDE',
        'CRUEL', 'CRUMB', 'CRUMP', 'CRUSH', 'CRUST', 'CRYPT', 'CUBIC', 'CUMIN', 'CURIO', 'CURLY', 'CURRY',
        'CURSE', 'CURVE', 'CYCLE', 'DAILY', 'DAIRY', 'DAISY', 'DANCE', 'DANDY', 'DEATH', 'DEBAR', 'DEBIT',
        'DEBUG', 'DEBUT', 'DECAL', 'DECAY', 'DECOR', 'DECOY', 'DECRY', 'DEFER', 'DEIGN', 'DELAY', 'DELTA',
        'DELVE', 'DEMON', 'DEMUR', 'DENIM', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DETER', 'DETOX', 'DEVIL',
        'DIARY', 'DIGIT', 'DILLY', 'DIMLY', 'DINER', 'DINGO', 'DINGY', 'DIRGE', 'DIRTY', 'DISCO', 'DITCH',
        'DITTO', 'DITTY', 'DIVER', 'DIZZY', 'DODGE', 'DODGY', 'DOGMA', 'DONOR', 'DOUBT', 'DOUGH', 'DOWDY',
        'DOWEL', 'DOWNY', 'DOWRY', 'DOZEN', 'DRAFT', 'DRAIN', 'DRAKE', 'DRAMA', 'DRANK', 'DRAPE', 'DRAWL',
        'DRAWN', 'DREAD', 'DREAM', 'DRESS', 'DRIED', 'DRIER', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROLL',
        'DRONE', 'DROOL', 'DROOP', 'DROSS', 'DROVE', 'DROWN', 'DRUID', 'DRUNK', 'DRYER', 'DRYLY', 'DUCHY',
        'DULLY', 'DUMMY', 'DUMPY', 'DUNCE', 'DUSKY', 'DUSTY', 'DUTCH', 'DUVET', 'DWARF', 'DWELL', 'DWELT',
        'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EASEL', 'EBONY', 'EDICT', 'EDIFY', 'EERIE', 'EIGHT',
        'EJECT', 'EKING', 'ELATE', 'ELBOW', 'ELDER', 'ELECT', 'ELEGY', 'ELFIN', 'ELIDE', 'ELITE', 'ELOPE',
        'ELUDE', 'EMAIL', 'EMBED', 'EMBER', 'EMCEE', 'EMPTY', 'ENACT', 'ENDOW', 'ENEMA', 'ENEMY', 'ENJOY',
        'ENNUI', 'ENSUE', 'ENTER', 'ENTRY', 'ENVOY', 'EPOCH', 'EPOXY', 'EQUAL', 'EQUIP', 'ERASE', 'ERECT',
        'ERROR', 'ERUPT', 'ESSAY', 'ETHER', 'ETHIC', 'EVADE', 'EVENT', 'EVERY', 'EVICT', 'EVOKE', 'EXACT',
        'EXALT', 'EXCEL', 'EXERT', 'EXILE', 'EXIST', 'EXPEL', 'EXTOL', 'EXTRA', 'EXULT', 'EYING', 'FABLE',
        'FACET', 'FAINT', 'FAIRY', 'FAITH', 'FALSE', 'FANCY', 'FATAL', 'FATTY', 'FAULT', 'FAUNA', 'FAVOR',
        'FEAST', 'FECAL', 'FEIGN', 'FELON', 'FEMME', 'FEMUR', 'FENCE', 'FERRY', 'FETAL', 'FETCH', 'FETID',
        'FEVER', 'FEWER', 'FIBER', 'FIBRE', 'FICUS', 'FIELD', 'FIEND', 'FIERY', 'FIFTH', 'FIFTY', 'FIGHT',
        'FILCH', 'FILET', 'FILLY', 'FILMY', 'FILTH', 'FINAL', 'FINCH', 'FINER', 'FIRST', 'FISHY', 'FIXER',
        'FIZZY', 'FJORD', 'FLACK', 'FLAIL', 'FLAIR', 'FLAKE', 'FLAKY', 'FLAME', 'FLANK', 'FLARE', 'FLASH',
        'FLASK', 'FLECK', 'FLEET', 'FLESH', 'FLICK', 'FLIER', 'FLING', 'FLINT', 'FLIRT', 'FLOAT', 'FLOCK',
        'FLOOD', 'FLOOR', 'FLORA', 'FLOSS', 'FLOUR', 'FLOUT', 'FLOWN', 'FLUFF', 'FLUID', 'FLUKE', 'FLUME',
        'FLUNG', 'FLUNK', 'FLUSH', 'FLUTE', 'FLYER', 'FOAMY', 'FOCAL', 'FOCUS', 'FOGGY', 'FOIST', 'FOLIO',
        'FOLLY', 'FORAY', 'FORCE', 'FORGE', 'FORGO', 'FORTE', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FOYER',
        'FRAIL', 'FRAME', 'FRANK', 'FRAUD', 'FREAK', 'FREED', 'FRESH', 'FRIAR', 'FRIED', 'FRILL', 'FRISK',
        'FRITZ', 'FROCK', 'FROND', 'FRONT', 'FROST', 'FROTH', 'FROWN', 'FROZE', 'FRUIT', 'FUDGE', 'FUMES',
        'FUNGI', 'FUNKY', 'FUNNY', 'FUROR', 'FURRY', 'FUSED', 'FUSSY', 'FUZZY', 'GAFFE', 'GAILY', 'GAMER',
        'GAMMA', 'GAMUT', 'GASSY', 'GAUDY', 'GAUGE', 'GAUNT', 'GAUZE', 'GAVEL', 'GAWKY', 'GAYER', 'GAYLY',
        'GAZER', 'GECKO', 'GEEKY', 'GEESE', 'GENIE', 'GENRE', 'GHOST', 'GHOUL', 'GIANT', 'GIDDY', 'GIRLY',
        'GIRTH', 'GIVEN', 'GIVER', 'GLADE', 'GLAND', 'GLARE', 'GLASS', 'GLAZE', 'GLEAM', 'GLEAN', 'GLIDE',
        'GLINT', 'GLOBE', 'GLOOM', 'GLORY', 'GLOSS', 'GLOVE', 'GLYPH', 'GNASH', 'GOLEM', 'GOLLY', 'GONAD',
        'GOODY', 'GOOEY', 'GOOFY', 'GOOSE', 'GORGE', 'GOUGE', 'GOURD', 'GRACE', 'GRADE', 'GRAFT', 'GRAIL',
        'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRATE', 'GRAVE', 'GRAVY', 'GRAZE', 'GREAT',
        'GREED', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIME', 'GRIMY', 'GRIND', 'GRIPE', 'GROAN', 'GROIN',
        'GROOM', 'GROPE', 'GROSS', 'GROUP', 'GROUT', 'GROVE', 'GROWL', 'GROWN', 'GRUEL', 'GRUFF', 'GRUMP',
        'GRUNT', 'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILE', 'GUILT', 'GUISE', 'GULCH', 'GULLY',
        'GUMBO', 'GUMMY', 'GUPPY', 'GUSTO', 'GUSTY', 'GYPSY', 'HABIT', 'HAIRY', 'HALVE', 'HANDY', 'HAPPY',
        'HARDY', 'HAREM', 'HARPY', 'HARRY', 'HARSH', 'HASTE', 'HASTY', 'HATCH', 'HATER', 'HAUNT', 'HAUTE',
        'HAVEN', 'HAVOC', 'HAZEL', 'HEADY', 'HEARD', 'HEART', 'HEATH', 'HEAVE', 'HEAVY', 'HEDGE', 'HEFTY',
        'HEIST', 'HELIX', 'HELLO', 'HENCE', 'HERON', 'HILLY', 'HINGE', 'HIPPO', 'HIPPY', 'HITCH', 'HOARD',
        'HOBBY', 'HOIST', 'HOLLY', 'HOMER', 'HONEY', 'HONOR', 'HORDE', 'HORNS', 'HORNY', 'HORSE', 'HOTEL',
        'HOTLY', 'HOUND', 'HOUSE', 'HOVEL', 'HOVER', 'HOWDY', 'HUMAN', 'HUMID', 'HUMOR', 'HUMPH', 'HUMUS',
        'HUNCH', 'HUNKY', 'HURRY', 'HUSKY', 'HUSSY', 'HUTCH', 'HYDRO', 'HYENA', 'HYPER', 'ICILY', 'ICING',
        'IDEAL', 'IDIOM', 'IDIOT', 'IDLER', 'IDYLL', 'IGLOO', 'IMAGE', 'IMBUE', 'IMPEL', 'IMPLY', 'INANE',
        'INBOX', 'INCUR', 'INDEX', 'INDIE', 'INEPT', 'INERT', 'INFER', 'INGOT', 'INLAY', 'INLET', 'INNER',
        'INPUT', 'INTER', 'INTRO', 'IONIC', 'IRATE', 'IRONY', 'ISLET', 'ISSUE', 'ITCHY', 'IVORY', 'JAUNT',
        'JAZZY', 'JELLY', 'JERKY', 'JETTY', 'JEWEL', 'JIFFY', 'JOINT', 'JOIST', 'JOKER', 'JOLLY', 'JOUST',
        'JUDGE', 'JUICE', 'JUICY', 'JUMBO', 'JUMPY', 'JUNTA', 'JUNTO', 'JUROR', 'KAPPA', 'KARMA', 'KAYAK',
        'KEBAB', 'KHAKI', 'KINKY', 'KIOSK', 'KITTY', 'KNACK', 'KNOLL', 'KOALA', 'KRILL', 'LABEL', 'LABOR',
        'LADEN', 'LADLE', 'LAGER', 'LAIRY', 'LAITY', 'LANCE', 'LANKY', 'LAPEL', 'LAPSE', 'LARGE', 'LARVA',
        'LASER', 'LASSO', 'LATCH', 'LATER', 'LATHE', 'LATTE', 'LAUGH', 'LAYER', 'LEACH', 'LEAFY', 'LEAKY',
        'LEANT', 'LEAPT', 'LEARN', 'LEASE', 'LEASH', 'LEAST', 'LEAVE', 'LEDGE', 'LEECH', 'LEERY', 'LEFTY',
        'LEGAL', 'LEGGY', 'LEMON', 'LEMUR', 'LEPER', 'LEVEL', 'LEVER', 'LIBEL', 'LIEGE', 'LIGHT', 'LIKEN',
        'LILAC', 'LIMBO', 'LIMIT', 'LINEN', 'LINER', 'LINGO', 'LIPID', 'LITHE', 'LIVER', 'LOCAL', 'LOCUS',
        'LODGE', 'LOFTY', 'LOGIC', 'LOGIN', 'LOOPY', 'LOOSE', 'LORRY', 'LOSER', 'LOUSE', 'LOUSY', 'LOVER',
        'LOWER', 'LOWLY', 'LOYAL', 'LUCID', 'LUCKY', 'LUMEN', 'LUMPY', 'LUNAR', 'LUNCH', 'LUNGE', 'LUPUS',
        'LURCH', 'LURID', 'LUSTY', 'LYING', 'LYMPH', 'LYRIC', 'MACHO', 'MACRO', 'MADAM', 'MADLY', 'MAFIA',
        'MAGIC', 'MAGMA', 'MAJOR', 'MAKER', 'MAMBO', 'MAMMA', 'MAMMY', 'MANGA', 'MANGE', 'MANGO', 'MANGY',
        'MANIA', 'MANIC', 'MANLY', 'MANOR', 'MAPLE', 'MARCH', 'MARRY', 'MARSH', 'MASON', 'MASSE', 'MATCH',
        'MATEY', 'MAUVE', 'MAXIM', 'MAYBE', 'MAYOR', 'MEALY', 'MEANT', 'MEATY', 'MECCA', 'MEDAL', 'MEDIA',
        'MEDIC', 'MELEE', 'MELON', 'MERCY', 'MERGE', 'MERIT', 'MERRY', 'METAL', 'METER', 'METRO', 'MICRO',
        'MIDGE', 'MIDST', 'MIGHT', 'MILKY', 'MIMIC', 'MINCE', 'MINER', 'MINIM', 'MINOR', 'MINTY', 'MINUS',
        'MIRTH', 'MISER', 'MISSY', 'MOCHA', 'MODEL', 'MODEM', 'MOLDY', 'MOLLY', 'MOMMA', 'MONEY', 'MONTH',
        'MOODY', 'MOOSE', 'MORAL', 'MORON', 'MORPH', 'MOSSY', 'MOTOR', 'MOTTO', 'MOUNT', 'MOURN', 'MOUSE',
        'MOUTH', 'MOVIE', 'MOWER', 'MUCKY', 'MUCUS', 'MUDDY', 'MULCH', 'MUMMY', 'MUNCH', 'MURAL', 'MURKY',
        'MUSHY', 'MUSIC', 'MUSKY', 'MUSTY', 'MYRRH', 'NADIR', 'NAIVE', 'NANNY', 'NASAL', 'NASTY', 'NATAL',
        'NAVAL', 'NAVEL', 'NEEDY', 'NEIGH', 'NERDY', 'NERVE', 'NEVER', 'NEWER', 'NEWLY', 'NICER', 'NICHE',
        'NIECE', 'NIGHT', 'NINJA', 'NINNY', 'NINTH', 'NOBLE', 'NOBLY', 'NOISE', 'NOISY', 'NOMAD', 'NOOSE',
        'NORTH', 'NOTCH', 'NOVEL', 'NUDGE', 'NURSE', 'NUTTY', 'NYLON', 'NYMPH', 'OAKEN', 'OBESE', 'OCCUR',
        'OCEAN', 'OCTAL', 'OCTET', 'ODDER', 'ODDLY', 'OFFAL', 'OFFER', 'OFTEN', 'OLDEN', 'OLDER', 'OLIVE',
        'OMEGA', 'ONION', 'ONSET', 'OPERA', 'OPINE', 'OPIUM', 'OPTIC', 'ORBIT', 'ORDER', 'ORGAN', 'OTHER',
        'OTTER', 'OUGHT', 'OUNCE', 'OUTDO', 'OUTER', 'OUTGO', 'OVARY', 'OVATE', 'OVERT', 'OVINE', 'OVOID',
        'OWING', 'OWNER', 'OXIDE', 'OZONE', 'PAINT', 'PALER', 'PALSY', 'PANEL', 'PANIC', 'PANSY', 'PAPAL',
        'PAPER', 'PARER', 'PARKA', 'PARRY', 'PARSE', 'PARTY', 'PASTA', 'PASTE', 'PASTY', 'PATCH', 'PATIO',
        'PATSY', 'PAUSE', 'PEACE', 'PEACH', 'PEARL', 'PEDAL', 'PENAL', 'PENCE', 'PENNE', 'PENNY', 'PERCH',
        'PERIL', 'PERKY', 'PESKY', 'PETAL', 'PETTY', 'PHASE', 'PHONE', 'PHONY', 'PHOTO', 'PIANO', 'PICKY',
        'PIECE', 'PIETY', 'PIGGY', 'PILOT', 'PINCH', 'PINEY', 'PINKY', 'PINTO', 'PIPER', 'PIQUE', 'PITCH',
        'PITHY', 'PIVOT', 'PIXEL', 'PIXIE', 'PIZZA', 'PLACE', 'PLAID', 'PLAIN', 'PLAIT', 'PLANE', 'PLANK',
        'PLANT', 'PLATE', 'PLAZA', 'PLEAD', 'PLEAT', 'PLIED', 'PLIER', 'PLUCK', 'PLUMB', 'PLUME', 'PLUMP',
        'PLUNK', 'PLUSH', 'POESY', 'POINT', 'POISE', 'POLAR', 'POLKA', 'POLYP', 'POOCH', 'POPPY', 'PORCH',
        'POSER', 'POSIT', 'POSSE', 'POUCH', 'POUND', 'POWER', 'PRANK', 'PRAWN', 'PREEN', 'PRESS', 'PRICE',
        'PRICK', 'PRIDE', 'PRIED', 'PRIME', 'PRIMO', 'PRINT', 'PRIOR', 'PRISM', 'PRIVY', 'PRIZE', 'PROBE',
        'PROOF', 'PROPS', 'PROUD', 'PROVE', 'PROWL', 'PROXY', 'PRUDE', 'PSALM', 'PUBIC', 'PUDGY', 'PUFFY',
        'PULPY', 'PULSE', 'PUNCH', 'PUPAL', 'PUPIL', 'PUPPY', 'PUREE', 'PURER', 'PURGE', 'PURSE', 'PUSHY',
        'PUTTY', 'PYGMY', 'QUACK', 'QUAIL', 'QUAKE', 'QUALM', 'QUARK', 'QUART', 'QUASH', 'QUASI', 'QUEEN',
        'QUEER', 'QUELL', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUILL', 'QUILT', 'QUIRK', 'QUITE',
        'QUOTA', 'QUOTE', 'QUOTH', 'RABBI', 'RABID', 'RACER', 'RADAR', 'RADII', 'RADIO', 'RAINY', 'RAISE',
        'RALLY', 'RALPH', 'RAMEN', 'RANCH', 'RANDY', 'RANGE', 'RAPID', 'RARER', 'RASPY', 'RATIO', 'RATTY',
        'RAVEN', 'RAYON', 'RAZOR', 'REACH', 'REACT', 'READY', 'REALM', 'REARM', 'REBAR', 'REBEL', 'REBUS',
        'REBUT', 'RECAP', 'RECUR', 'RECUT', 'REEDY', 'REFER', 'REGAL', 'REHAB', 'REIGN', 'RELAX', 'RELAY',
        'RELIC', 'REMIT', 'RENAL', 'RENEW', 'REPAY', 'REPEL', 'REPLY', 'RERUN', 'RESET', 'RESIN', 'RETCH',
        'RETRO', 'RETRY', 'REUSE', 'REVEL', 'REVUE', 'RHINO', 'RHYME', 'RIDER', 'RIDGE', 'RIFLE', 'RIGHT',
        'RIGID', 'RIGOR', 'RINSE', 'RIPEN', 'RIPER', 'RISEN', 'RISER', 'RISKY', 'RIVER', 'RIVET', 'ROACH',
        'ROAST', 'ROBIN', 'ROBOT', 'ROCKY', 'RODEO', 'ROGER', 'ROGUE', 'ROOMY', 'ROOST', 'ROTOR', 'ROUGH',
        'ROUND', 'ROUSE', 'ROUTE', 'ROVER', 'ROWDY', 'ROWER', 'ROYAL', 'RUDDY', 'RULER', 'RUMBA', 'RUMOR',
        'RUPEE', 'RURAL', 'RUSTY', 'SADLY', 'SAFER', 'SAINT', 'SALAD', 'SALON', 'SALSA', 'SALTY', 'SALVE',
        'SALVO', 'SANDY', 'SANER', 'SAPPY', 'SASSY', 'SATIN', 'SATYR', 'SAUCE', 'SAUCY', 'SAUNA', 'SAUTE',
        'SAVOR', 'SAVVY', 'SCALD', 'SCALE', 'SCALP', 'SCALY', 'SCAMP', 'SCANT', 'SCARE', 'SCARF', 'SCARY',
        'SCENE', 'SCENT', 'SCOFF', 'SCOLD', 'SCONE', 'SCOOP', 'SCOOT', 'SCORE', 'SCORN', 'SCOUR', 'SCOUT',
        'SCOWL', 'SCRAM', 'SCRAP', 'SCREE', 'SCREW', 'SCRUB', 'SCRUM', 'SCUBA', 'SEDAN', 'SEEDY', 'SEGUE',
        'SEIZE', 'SEMEN', 'SENSE', 'SEPIA', 'SERIF', 'SERUM', 'SERVE', 'SETUP', 'SEVEN', 'SEVER', 'SEWER',
        'SHACK', 'SHADE', 'SHADY', 'SHAFT', 'SHAKE', 'SHAKY', 'SHALE', 'SHALL', 'SHALT', 'SHAME', 'SHANK',
        'SHAPE', 'SHARD', 'SHARE', 'SHARK', 'SHARP', 'SHAVE', 'SHAWL', 'SHEAR', 'SHEEN', 'SHEEP', 'SHEER',
        'SHEET', 'SHEIK', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHINY', 'SHIRE', 'SHIRK', 'SHIRT', 'SHOAL',
        'SHOCK', 'SHONE', 'SHOOK', 'SHOOT', 'SHORE', 'SHORN', 'SHORT', 'SHOUT', 'SHOVE', 'SHOWN', 'SHOWY',
        'SHRED', 'SHREW', 'SHRUB', 'SHRUG', 'SIEGE', 'SIEVE', 'SIGHT', 'SIGMA', 'SILKY', 'SILLY', 'SINCE',
        'SINUS', 'SIXTH', 'SIXTY', 'SKATE', 'SKIER', 'SKIFF', 'SKILL', 'SKIMP', 'SKIRT', 'SKULK', 'SKULL',
        'SKUNK', 'SLACK', 'SLAIN', 'SLANG', 'SLANT', 'SLASH', 'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLEET',
        'SLEPT', 'SLICE', 'SLICK', 'SLIDE', 'SLIME', 'SLIMY', 'SLING', 'SLINK', 'SLOOP', 'SLOPE', 'SLOSH',
        'SLOTH', 'SLUMP', 'SLUNG', 'SLUNK', 'SLURP', 'SLUSH', 'SLYLY', 'SMACK', 'SMALL', 'SMART', 'SMASH',
        'SMEAR', 'SMELL', 'SMELT', 'SMILE', 'SMIRK', 'SMITE', 'SMITH', 'SMOCK', 'SMOKE', 'SMOKY', 'SMOTE',
        'SNACK', 'SNAIL', 'SNAKE', 'SNAKY', 'SNARE', 'SNARL', 'SNEAK', 'SNEER', 'SNIDE', 'SNIFF', 'SNIPE',
        'SNORE', 'SNORT', 'SNOUT', 'SNOWY', 'SNUCK', 'SNUFF', 'SOAPY', 'SOBER', 'SOGGY', 'SOLAR', 'SOLID',
        'SOLVE', 'SONAR', 'SONIC', 'SOOTH', 'SOOTY', 'SORRY', 'SOUND', 'SOUTH', 'SOWER', 'SPACE', 'SPADE',
        'SPANK', 'SPARE', 'SPARK', 'SPASM', 'SPAWN', 'SPEAK', 'SPEAR', 'SPECK', 'SPEED', 'SPELL', 'SPELT',
        'SPEND', 'SPENT', 'SPERM', 'SPICE', 'SPICY', 'SPIED', 'SPIEL', 'SPIKE', 'SPIKY', 'SPILL', 'SPILT',
        'SPINE', 'SPINY', 'SPIRE', 'SPITE', 'SPLAT', 'SPLIT', 'SPOIL', 'SPOKE', 'SPOOF', 'SPOOK', 'SPOOL',
        'SPOON', 'SPORE', 'SPORT', 'SPOUT', 'SPRAY', 'SPREE', 'SPRIG', 'SPUNK', 'SPURN', 'SPURT', 'SQUAD',
        'SQUAT', 'SQUIB', 'STACK', 'STAFF', 'STAGE', 'STAID', 'STAIN', 'STAIR', 'STAKE', 'STALE', 'STALK',
        'STALL', 'STAMP', 'STAND', 'STANK', 'STARE', 'STARK', 'START', 'STASH', 'STATE', 'STAVE', 'STEAD',
        'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP', 'STEER', 'STEIN', 'STERN', 'STICK', 'STIFF', 'STILL',
        'STILT', 'STING', 'STINK', 'STINT', 'STOCK', 'STOIC', 'STOKE', 'STOLE', 'STOMP', 'STONE', 'STONY',
        'STOOD', 'STOOL', 'STOOP', 'STORE', 'STORK', 'STORM', 'STORY', 'STOUT', 'STOVE', 'STRAP', 'STRAW',
        'STRAY', 'STRIP', 'STRUT', 'STUCK', 'STUDY', 'STUFF', 'STUMP', 'STUNG', 'STUNK', 'STUNT', 'STYLE',
        'SUAVE', 'SUGAR', 'SUING', 'SUITE', 'SULKY', 'SULLY', 'SUMAC', 'SUNNY', 'SUPER', 'SURER', 'SURGE',
        'SURLY', 'SUSHI', 'SWAMI', 'SWAMP', 'SWARM', 'SWASH', 'SWATH', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET',
        'SWELL', 'SWEPT', 'SWIFT', 'SWILL', 'SWINE', 'SWING', 'SWIRL', 'SWISH', 'SWOON', 'SWOOP', 'SWORD',
        'SWORE', 'SWORN', 'SYRUP', 'TABBY', 'TABLE', 'TABOO', 'TACIT', 'TACKY', 'TAFFY', 'TAINT', 'TAKER',
        'TALLY', 'TALON', 'TAMER', 'TANGO', 'TANGY', 'TAPER', 'TAPIR', 'TARDY', 'TASTE', 'TASTY', 'TATTY',
        'TAUNT', 'TAWNY', 'TEACH', 'TEARY', 'TEASE', 'TEDDY', 'TEETH', 'TEMPO', 'TENET', 'TENOR', 'TENSE',
        'TENTH', 'TEPEE', 'TEPID', 'TERRA', 'TERSE', 'TESTY', 'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE',
        'THESE', 'THETA', 'THICK', 'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THONG', 'THORN', 'THOSE',
        'THREE', 'THREW', 'THROB', 'THROW', 'THRUM', 'THUMB', 'THUMP', 'THYME', 'TIARA', 'TIBIA', 'TIDAL',
        'TIGER', 'TIGHT', 'TILDE', 'TIMER', 'TIMID', 'TIPSY', 'TITAN', 'TITHE', 'TITLE', 'TOAST', 'TODAY',
        'TODDY', 'TOKEN', 'TONAL', 'TONGA', 'TONIC', 'TOOTH', 'TOPAZ', 'TOPIC', 'TORCH', 'TORSO', 'TORTE',
        'TOTAL', 'TOTEM', 'TOUCH', 'TOUGH', 'TOWEL', 'TOWER', 'TOXIC', 'TOXIN', 'TRACE', 'TRACK', 'TRACT',
        'TRADE', 'TRAIL', 'TRAIN', 'TRAIT', 'TRAMP', 'TRASH', 'TRAWL', 'TREAD', 'TREAT', 'TREND', 'TRIAD',
        'TRIAL', 'TRIBE', 'TRICE', 'TRICK', 'TRIED', 'TRIPE', 'TRITE', 'TROLL', 'TROOP', 'TROPE', 'TROUT',
        'TROVE', 'TRUCE', 'TRUCK', 'TRUER', 'TRULY', 'TRUMP', 'TRUNK', 'TRUSS', 'TRUST', 'TRUTH', 'TRYST',
        'TUBAL', 'TUBER', 'TULIP', 'TULLE', 'TUMOR', 'TUNIC', 'TURBO', 'TUTOR', 'TWANG', 'TWEAK', 'TWEED',
        'TWEET', 'TWICE', 'TWINE', 'TWIRL', 'TWIST', 'TWIXT', 'TYING', 'UDDER', 'ULCER', 'ULTRA', 'UNCLE',
        'UNCUT', 'UNDER', 'UNDID', 'UNDUE', 'UNFED', 'UNFIT', 'UNIFY', 'UNITE', 'UNMET', 'UNTIE', 'UNTIL',
        'UNWED', 'UNZIP', 'UPPER', 'UPSET', 'URBAN', 'URINE', 'USAGE', 'USHER', 'USING', 'USUAL', 'USURP',
        'UTILE', 'UTTER', 'VAGAL', 'VAGUE', 'VALET', 'VALID', 'VALOR', 'VALUE', 'VALVE', 'VAPID', 'VAPOR',
        'VAULT', 'VAUNT', 'VEGAN', 'VENOM', 'VENUE', 'VERGE', 'VERSE', 'VERSO', 'VERVE', 'VIDEO', 'VIGIL',
        'VIGOR', 'VILLA', 'VINYL', 'VIOLA', 'VIPER', 'VIRAL', 'VIRUS', 'VISIT', 'VISOR', 'VISTA', 'VITAL',
        'VIVID', 'VIXEN', 'VOCAL', 'VODKA', 'VOGUE', 'VOICE', 'VOILA', 'VOMIT', 'VOTER', 'VOUCH', 'VOWEL',
        'VYING', 'WACKY', 'WAFER', 'WAGER', 'WAGON', 'WAIST', 'WAIVE', 'WALTZ', 'WASTE', 'WATCH', 'WATER',
        'WAVER', 'WAXEN', 'WEARY', 'WEAVE', 'WEDGE', 'WEIGH', 'WEIRD', 'WHACK', 'WHALE', 'WHARF', 'WHEAT',
        'WHEEL', 'WHELP', 'WHERE', 'WHICH', 'WHIFF', 'WHILE', 'WHINE', 'WHINY', 'WHIRL', 'WHITE', 'WHOLE',
        'WHOOP', 'WHORE', 'WHORL', 'WIDEN', 'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WIGHT', 'WILLY', 'WIMPY',
        'WINCE', 'WINCH', 'WINDY', 'WISER', 'WISPY', 'WITCH', 'WITTY', 'WOKEN', 'WOMAN', 'WOMEN', 'WORLD',
        'WORMS', 'WORMY', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRACK', 'WRATH', 'WREAK',
        'WRECK', 'WREST', 'WRING', 'WRIST', 'WRITE', 'WRONG', 'WROTE', 'WRUNG', 'YACHT', 'YEARN', 'YEAST',
        'YIELD', 'YOUNG', 'YOUTH', 'ZEBRA', 'ZESTY', 'ZONAL',
    ],
    6 => [
        'ABACUS', 'ABOUND', 'ABSENT', 'ABSORB', 'ACCENT', 'ACCEPT', 'ACCESS', 'ACCORD', 'ACCRUE', 'ACCUSE',
        'ACETIC', 'ACHING', 'ACIDIC', 'ACROSS', 'ACTION', 'ACTIVE', 'ACTUAL', 'ADAGIO', 'ADAPTS', 'ADDICT',
        'ADJOIN', 'ADJUST', 'ADMIRE', 'ADVENT', 'ADVICE', 'ADVISE', 'AERATE', 'AFFAIR', 'AFFECT', 'AFFIRM',
        'AFFORD', 'AFLOAT', 'AFRAID', 'AGENCY', 'AGENDA', 'AGHAST', 'AGREED', 'ALARMS', 'ALBINO', 'ALCOVE',
        'ALIGHT', 'ALLEGE', 'ALLIED', 'ALLOWS', 'ALLUDE', 'ALLURE', 'ALMOND', 'ALPINE', 'ALTARS', 'AMAZED',
        'AMBUSH', 'AMENDS', 'AMIDST', 'AMOUNT', 'AMUSED', 'ANALOG', 'ANCHOR', 'ANEMIC', 'ANGLED', 'ANIMAL',
        'ANKLET', 'ANNOYS', 'ANNUAL', 'ANOINT', 'ANSWER', 'ANTHEM', 'ANTICS', 'ANVILS', 'ANYHOW', 'ANYONE',
        'APACHE', 'APATHY', 'APOLLO', 'APPEAL', 'APPEAR', 'APPEND', 'ARCADE', 'ARCHER', 'ARCHLY', 'ARDENT',
        'ARGUED', 'ARISEN', 'ARMFUL', 'ARMORY', 'AROMAS', 'AROUND', 'AROUSE', 'ARREST', 'ARRIVE', 'ARTERY',
        'ARTFUL', 'ARTIST', 'ASCEND', 'ASPECT', 'ASSAIL', 'ASSENT', 'ASSERT', 'ASSESS', 'ASSETS', 'ASSIGN',
        'ASSIST', 'ASSUME', 'ASSURE', 'ASTERN', 'ASTHMA', 'ASYLUM', 'ATOMIC', 'ATTACH', 'ATTACK', 'ATTAIN',
        'ATTEND', 'ATTEST', 'AUBURN', 'AUDITS', 'AUGUST', 'AUTHOR', 'AUTUMN', 'AVATAR', 'AVENGE', 'AVENUE',
        'AVERSE', 'AVIARY', 'AVOIDS', 'AWAKEN', 'AWARDS', 'AWHILE', 'AXIOMS', 'AZALEA', 'BABBLE', 'BACKED',
        'BADGER', 'BAFFLE', 'BAGFUL', 'BAGPIP', 'BAKERY', 'BALCON', 'BALLET', 'BALLOT', 'BAMBOO', 'BANANA',
        'BANDIT', 'BANGLE', 'BANISH', 'BANKER', 'BANNER', 'BARBED', 'BARBER', 'BARELY', 'BARREL', 'BARTER',
        'BASICS', 'BASKET', 'BATHOS', 'BATTLE', 'BAUBLE', 'BAZOOK', 'BEACON', 'BEAKER', 'BEATEN', 'BEAUTY',
        'BECKON', 'BEDLAM', 'BEDPAN', 'BEEFED', 'BEFALL', 'BEFITS', 'BEFORE', 'BEGGAR', 'BEGINS', 'BEHALF',
        'BEHAVE', 'BEHEAD', 'BEHEST', 'BEHOLD', 'BELIEF', 'BELLOW', 'BELONG', 'BENIGN', 'BERATE', 'BEREFT',
        'BESIDE', 'BESTOW', 'BETRAY', 'BETTER', 'BIASED', 'BICKER', 'BIFOLD', 'BIGOTS', 'BILLOW', 'BINARY',
        'BINDER', 'BIOPIC', 'BIPEDS', 'BISHOP', 'BITING', 'BITTEN', 'BITTER', 'BLAZER', 'BLEACH',
        'BLEARY', 'BLIGHT', 'BLONDE', 'BLOTCH', 'BLOWER', 'BLUESY', 'BLUFFS', 'BLUNTS', 'BLURBS', 'BOASTS',
        'BOBCAT', 'BODICE', 'BODILY', 'BOMBED', 'BONNET', 'BOOGER', 'BOOKED', 'BOOMED', 'BOOTED', 'BORDER',
        'BORING', 'BORROW', 'BOTANY', 'BOTHER', 'BOTTLE', 'BOTTOM', 'BOUGHT', 'BOUNCE', 'BOUNCY', 'BONDER',
        'BOURSE', 'BOWING', 'BOWLER', 'BOXING', 'BRACER', 'BRAIDS', 'BRANCH', 'BRANDY', 'BRAWNY', 'BREACH',
        'BREATH', 'BREEZE', 'BREEZY', 'BRIBED', 'BRIDGE', 'BRIGHT', 'BRIMLY', 'BRUNCH',
    ],
    7 => [
        'ABDOMEN', 'ABILITY', 'ABSENCE', 'ACADEMY', 'ACCOUNT', 'ACCUSED', 'ACHIEVE', 'ACOLYTE', 'ACQUIRE', 'ACROBAT',
        'ADAPTER', 'ADDRESS', 'ADMIRED', 'ADVERSE', 'ADVISER', 'AEROBIC', 'AFFABLE', 'AFFRONT', 'AGAINST', 'AIRFLOW',
        'AIRPORT', 'ALCHEMY', 'ALGEBRA', 'ALIGNED', 'ALLERGY', 'ALLOWED', 'ALMANAC', 'ALREADY', 'ALRIGHT', 'AMATEUR',
        'AMAZING', 'AMNESTY', 'ANALYST', 'ANCHORS', 'ANCIENT', 'ANEMONE', 'ANGELIC', 'ANIMATE', 'ANOTHER', 'ANTENNA',
        'ANTIQUE', 'ANXIETY', 'ANYBODY', 'ANYTIME', 'APOLOGY', 'APPROVE', 'ARCHWAY', 'ARDUOUS', 'AROUSED', 'ARRANGE',
        'ARRIVAL', 'ARTISAN', 'ARTWORK', 'ASHAMED', 'ASPHALT', 'ASSERTS', 'ASSUMED', 'ASTOUND', 'ATHLETE', 'ATOMIZE',
        'ATTACHE', 'ATTEMPT', 'ATTRACT', 'AUCTION', 'AUDIBLE', 'AUGMENT', 'AUSTERE', 'AUTHORS', 'AUTOPSY', 'AVARICE',
        'BACKLOG', 'BAGGAGE', 'BALANCE', 'BANDAGE', 'BANKING', 'BANQUET', 'BARGAIN', 'BARRACK', 'BARRIER', 'BARTEND',
        'BATHING', 'BATTERY', 'BECAUSE', 'BEDROOM', 'BELIEVE', 'BENEATH', 'BENEFIT', 'BETWEEN', 'BICYCLE', 'BILLION',
        'BIOLOGY', 'BISCUIT', 'BLANKET', 'BLOCKED', 'BLOSSOM', 'BOARDER', 'BOLSTER', 'BOOKEND', 'BOOKING', 'BOOKLET',
        'BOOMING', 'BOOSTER', 'BOROUGH', 'BOTTLED', 'BOUNDER', 'BOYCOTT', 'BRACKET', 'BRAVERY', 'BREATHE', 'BREEZED',
        'BRIGADE', 'BRISKET', 'BROUGHT', 'BROWNIE', 'BRUISER', 'BUFFALO', 'BUILDER', 'BULKIER', 'BURNISH', 'BUSIEST',
        'CABBAGE', 'CABINET', 'CALCIFY', 'CALIBER', 'CALLING', 'CALORIC', 'CANTEEN', 'CAPTION', 'CAPTURE', 'CARAVAN',
        'CAREFUL', 'CARNAGE', 'CARRIER', 'CARTOON', 'CARVING', 'CASCADE', 'CASHIER', 'CASINGS', 'CATALOG', 'CAUTION',
    ],
    8 => [
        'ABSOLUTE', 'ABSTRACT', 'ACADEMIC', 'ACCURATE', 'ACHIEVED', 'ACOUSTIC', 'ACTIVATE', 'ADAPTIVE', 'ADDITION',
        'ADEQUATE', 'ADJACENT', 'ADVANCED', 'ADVISORY', 'AEROSOLS', 'AFFLUENT', 'AIRBORNE', 'ALLOCATE', 'ANALYSIS',
        'ANNOUNCE', 'APPROACH', 'ARTIFACT', 'ASSEMBLY', 'ASSIGNED', 'ASTEROID', 'ATHLETIC', 'ATTACHED', 'ATTACKER',
        'ATTEMPTS', 'ATTITUDE', 'ATTORNEY', 'AUDIENCE', 'AUTOMATE', 'AUTUMNAL',         'AVENGERS', 'BACKFIRE', 'BACKPACK',
        'BAREFOOT', 'BASEBALL', 'BATHROOM', 'BANKNOTE', 'BEVERAGE', 'BICYCLES', 'BIRTHDAY', 'BLUEBELL', 'BOOKCASE',
        'BOOKMARK', 'BOUTIQUE', 'BASEMENT', 'BARRELED', 'BINDINGS', 'CASSETTE', 'CATEGORY', 'CAUTIOUS', 'CELLULAR',
        'CHAMPION', 'CHEMICAL', 'CHILDREN', 'CIRCUITS', 'CLASSIFY', 'COLLAPSE', 'COLONIAL', 'COMBINED', 'COMMENCE',
    ],
];
